### ISSUE TITLE
izpis cikla

### ISSUE THREAD

**Issue by TilenHumar** [TilenHumar/Bitonic-TSP#2]
Pozdravljeni,

potreboval bi pomoč pri izpisu cikla. V while zanki v funkciji za izpis (bitonic_TSP_algoritem.R) nisem prepričan, kaj nastaviti za spremenljivko "trenutno", da se izpisovanje nadaljuje pravilno. 
Hvala za razumevanje in lep pozdrav.

Tilen Humar

**Comment by jaanos** [comment]
Če prav razumem, vrednost `C[1, j]` pove predhodnika `j`-tega vozlišča v poti, ki se začne v prvem vozlišču (in tako pokrije vsa vozlišča). Glede na to bi bila nastavitev `trenutni <- C[1, trenutni]` ustrezna - premaknemo se namreč na predhodnika trenutnega vozlišča. Seveda bo vrnjena pot v obratnem vrstnem redu - za obračanje se lahko uporabi funkcija `rev`.

Algoritem trenutno začne pri `N`-tem vozlišču - če je to vedno zadnje, je tako seveda v redu. V nasprotnem primeru bi bilo potrebno povedati še, kje naj se iskanje začne (ali pa se to ugotovi iz manjkajočega indeksa).

**Comment by TilenHumar** [comment]
Pozdravljeni,

rabil bi še pomoč pri samem algoritmu, saj vrne pravo končno dolžino cikla, vmesni rezultati pa so napačni (npr. bitonic_TSP_algoritem.R, primer na koncu, člen B[1,3] bi moral biti razdalja(a_1, a_2) + razdalja(a_2 + a_3) ), zato je posledično narisan napačen cikel.
Vesel bi bil kakšnega nasveta ali komentarja.

Lep pozdrav

**Comment by jaanos** [comment]
Nisem čisto prepričan, če razumem, kako naj bi vajin algoritem deloval - ali naj bi sledil Algoritmu 1 na strani 12 v članku?

Če poskusim razumeti, kaj se dogaja:
https://github.com/TilenHumar/Bitonic-TSP/blob/4d02d3345c015ac28786523f5732ff9d13e9cc4a/bitonic_TSP_algoritem.R#L21-L38
* V vrsticah 24-25 dobita dolžino poti od vozlišča *i* do vozlišča *j* kot vsoto dolžine poti od *i* do *j*-1 in razdaljo med *j*-1 in *j*. Prednika *j* potem nastavita na *j*-1, kar izgleda v redu.
* V vrsticah 28-29 dobita dolžino poti od vozlišča *j*-1 do vozlišča *j* kot vsoto dolžine poti od *i* do *j-1* in razdaljo med *i* in *j*. Če prav razumem, gre tukaj potem za obratno pot, tako da prednika *j* nastavita na *i*. Spremenljivko *i* tukaj sicer uporabita izven zanke, kjer je bila definirana, in ima tako vrednost *j*-2 - ali je to v redu?
* V vrsticah 32-36 dobita dolžino poti od vozlišča *i* = *j*-2 do vozlišča *j* kot vsoto dolžine poti od nekega *k* do *j*-1 in razdaljo med *k* in *j*. Spet gre tu za obratno pot, tako da prednika *j* nastavita na *k*, kar tudi izgleda v redu.

Predniki torej izgledajo pravilno nastavljeni - edino glede uporabe *i* nisem prepričan, ali s tem dosežeta želeno.

**Comment by jaanos** [comment]
Vidim, da je prejšnji komentar izbrisan - ali sta uspela razrešiti težavo?

**Comment by TilenHumar** [comment]
Sva popravila, matriko B zdaj vrne pravilno.

**Comment by TilenHumar** [comment]
Pozdravljeni,
še vedno imava težave pri izpisovanju cikla.
https://github.com/TilenHumar/Bitonic-TSP/blob/e088664b9f2a2a46635761e67f0fd53fc227b469/bitonic_TSP_algoritem.R#L49-L69
Funkcija občasno vrne pravilen cikel, sicer pa je rešitev očitno napačna. Problem je, da pri pregledu od N do 1 ne more beležiti zaporednih točk (npr. x koordinate 5 in 4, saj C[4,5] != 4).

**Comment by jaanos** [comment]
Nekako tako bi šlo:
```R
izpisi_cikel <- function(C, seznam_tock){
  N <- nrow(seznam_tock)
  pot <- c(N, N-1)
  
  trenutni <- C[N-1, N]
  
  while (trenutni > 1) {
    pot <- c(trenutni, pot)
    if (trenutni < pot[2] - 1) {
      pot <- rev(pot)
    }
    trenutni <- C[pot[length(pot)], pot[1]]
  }
  return(c(setdiff(N:1, pot), pot))
}
```
Ideja je, da se pot gradi z obeh strani: če je v bitonični poti od `i` do `j` predzadnje vozlišče `j-1`, potem ga postavita pred `j` in gradita pot od `i` do `j-1`, če pa je predzadnje vozlišče `k < j-1` (kar zaradi rekurzivnih enačb implicira tudi `k < i = j-1`), pa bo treba graditi pot od `k` do `i` - vloga začetka in konca poti se tukaj obrne, zato celotno do sedaj zgrajeno pot obrnemo. Zanka se ustavi, ko je doseženo vozlišče `1` - manjkajoča vozlišča je potem še potrebno dodati v cikel (v padajočem vrstnem redu, saj imamo trenutni konec vedno na začetku grajene poti).

**Comment by TilenHumar** [comment]
Razumem, hvala za pomoč.
